title: "Jim's Random Stuff"
author: "Jim Drygiannakis"
description: "Random stuff I'm interested in."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
domain: jdryg.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jdryg.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true              # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Website, icon: globe, url: "https://makingartstudios.com/"}
  - {title: Github, icon: github, url: "https://github.com/jdryg"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
